# Generated by Django 4.0.4 on 2022-11-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_skill_alter_company_options_alter_duty_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.RemoveField(
            model_name='duty',
            name='skills',
        ),
        migrations.AddField(
            model_name='role',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='duties', to='about.skill'),
        ),
    ]
