# Generated by Django 4.0.4 on 2022-11-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_skill_options_remove_duty_skills_role_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
